export const seedCategories = [
  {
    name: 'Cakes',
    slug: 'cakes',
    description: 'Celebration masterpieces, layered to perfection with rich cream and handcrafted chocolate.',
    icon: 'Cake',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    displayOrder: 1,
    isActive: true,
  },
  {
    name: 'Biscuits',
    slug: 'biscuits',
    description: 'Crispy perfection, buttery tea rusks, cashew crunch, and melt-in-mouth cookies.',
    icon: 'Cookie',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80',
    displayOrder: 2,
    isActive: true,
  },
  {
    name: 'Breads',
    slug: 'breads',
    description: 'Freshly baked daily artisanal sourdough, garlic loaves, multigrain, and milk bread.',
    icon: 'Croissant',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    displayOrder: 3,
    isActive: true,
  },
  {
    name: 'Pastries',
    slug: 'pastries',
    description: 'Delicate flaky layers, French choux, velvety mousses, and luscious fruit glazes.',
    icon: 'IceCream',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    displayOrder: 4,
    isActive: true,
  },
  {
    name: 'Snacks',
    slug: 'snacks',
    description: 'Savory bakery favorites, crispy samosas, spiced paneer pockets, and golden savory bites.',
    icon: 'UtensilsCrossed',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    displayOrder: 5,
    isActive: true,
  },
  {
    name: 'Puffs',
    slug: 'puffs',
    description: 'Golden, flaky goodness baked fresh every hour with delectable savory fillings.',
    icon: 'Flame',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    displayOrder: 6,
    isActive: true,
  },
];

export const seedProductsData = [
  // ================= CAKES (5+) =================
  {
    name: 'Chocolate Truffle Cake',
    categoryName: 'Cakes',
    description: 'Dense, velvety chocolate sponge coated in a luscious dark Belgian chocolate ganache.',
    price: 599,
    weight: '500g',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['Dark Belgian Cocoa', 'Whipped Cream', 'Vanilla Extract', 'Brown Sugar', 'Flour'],
    nutritionalInfo: { calories: '340 kcal / slice', servings: '4-6 Slices', shelfLife: '3 Days Refrigerated' },
  },
  {
    name: 'Black Forest Royale Cake',
    categoryName: 'Cakes',
    description: 'Classic cocoa sponge layered with whipped vanilla frosting, sweet red cherries, and bittersweet chocolate shavings.',
    price: 549,
    weight: '500g',
    image: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Dark Chocolate', 'Morello Cherries', 'Dairy Whipped Cream', 'Cocoa Butter'],
    nutritionalInfo: { calories: '310 kcal / slice', servings: '4-6 Slices', shelfLife: '2-3 Days' },
  },
  {
    name: 'Red Velvet Heart Cake',
    categoryName: 'Cakes',
    description: 'Velvety crimson buttermilk sponge balanced with silky Philadelphia-style cream cheese frosting.',
    price: 649,
    weight: '500g',
    image: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Buttermilk', 'Cream Cheese', 'Cocoa Powder', 'Natural Beet Extract', 'Pure Butter'],
    nutritionalInfo: { calories: '325 kcal / slice', servings: '4-6 Slices', shelfLife: '3 Days' },
  },
  {
    name: 'Butterscotch Crunch Cake',
    categoryName: 'Cakes',
    description: 'Moist golden sponge crowned with handcrafted caramelized praline crunch and golden butterscotch drizzle.',
    price: 499,
    weight: '500g',
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Caramelized Praline', 'Butterscotch Essence', 'Whipped Cream', 'Sponge Flour'],
    nutritionalInfo: { calories: '295 kcal / slice', servings: '4-6 Slices', shelfLife: '3 Days' },
  },
  {
    name: 'Pineapple Glaze Gateau',
    categoryName: 'Cakes',
    description: 'Light vanilla sponge enriched with freshly chopped tropical pineapple compote and a delicate glaze.',
    price: 479,
    weight: '500g',
    image: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['Tropical Pineapple', 'Chantilly Cream', 'Vanilla Sponge', 'Glaze Jelly'],
    nutritionalInfo: { calories: '270 kcal / slice', servings: '4-6 Slices', shelfLife: '2 Days' },
  },

  // ================= BISCUITS (5+) =================
  {
    name: 'Artisanal Osmania Butter Biscuits',
    categoryName: 'Biscuits',
    description: 'The legendary sweet and savory melt-in-the-mouth butter biscuit, baked fresh to golden perfection.',
    price: 149,
    weight: '250g (16 pcs)',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['Pure Desi Ghee', 'Wheat Flour', 'Sea Salt', 'Cardamom', 'Milk Solids'],
    nutritionalInfo: { calories: '85 kcal / biscuit', servings: '16 Biscuits', shelfLife: '30 Days' },
  },
  {
    name: 'Cashew Badam Crunch Cookies',
    categoryName: 'Biscuits',
    description: 'Golden, crumbly shortbread cookies laden with toasted whole California almonds and Goan cashews.',
    price: 189,
    weight: '250g (12 pcs)',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Toasted Almonds', 'Roasted Cashews', 'Butter', 'Brown Cane Sugar'],
    nutritionalInfo: { calories: '110 kcal / cookie', servings: '12 Cookies', shelfLife: '45 Days' },
  },
  {
    name: 'Fruit & Nut Crunchy Rusks',
    categoryName: 'Biscuits',
    description: 'Double-baked crispy tea rusks infused with candied fruits, fennel seeds, and sliced almonds.',
    price: 129,
    weight: '300g',
    image: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Whole Wheat', 'Candied Papaya Fruits', 'Fennel Seeds', 'Milk', 'Butter'],
    nutritionalInfo: { calories: '65 kcal / rusk', servings: '18 Rusks', shelfLife: '60 Days' },
  },
  {
    name: 'Belgian Choco-Chip Butter Cookies',
    categoryName: 'Biscuits',
    description: 'Buttery bakery cookies studded generously with bittersweet 55% Belgian chocolate morsels.',
    price: 169,
    weight: '250g',
    image: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Belgian Chocolate Chips', 'Butter', 'Brown Sugar', 'Wheat Flour', 'Vanilla'],
    nutritionalInfo: { calories: '95 kcal / cookie', servings: '14 Cookies', shelfLife: '30 Days' },
  },
  {
    name: 'Toasted Coconut Macaroon Biscuits',
    categoryName: 'Biscuits',
    description: 'Chewy center with a crisp golden exterior, made with desiccated aromatic coastal coconut.',
    price: 139,
    weight: '250g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['Desiccated Coconut', 'Condensed Milk', 'Cardamom', 'Butter'],
    nutritionalInfo: { calories: '90 kcal / piece', servings: '12 Pieces', shelfLife: '20 Days' },
  },

  // ================= BREADS (5+) =================
  {
    name: 'Artisanal Country Sourdough Loaf',
    categoryName: 'Breads',
    description: 'Naturally fermented 36-hour sourdough with a golden blistered crust and an airy, open crumb.',
    price: 180,
    weight: '400g Loaf',
    image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['Stoneground Flour', 'Wild Sourdough Starter', 'Himalayan Pink Salt', 'Filtered Water'],
    nutritionalInfo: { calories: '160 kcal / 2 slices', servings: '10 Slices', shelfLife: '4 Days' },
  },
  {
    name: 'Roasted Garlic & Herb Focaccia',
    categoryName: 'Breads',
    description: 'Olive-oil drenched Italian flatbread topped with slow-roasted garlic cloves, rosemary, and sea salt flakes.',
    price: 160,
    weight: '350g',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Extra Virgin Olive Oil', 'Roasted Garlic', 'Fresh Rosemary', 'Sea Salt', 'Flour'],
    nutritionalInfo: { calories: '190 kcal / portion', servings: '6 Portions', shelfLife: '3 Days' },
  },
  {
    name: 'Whole Wheat 7-Grain Health Bread',
    categoryName: 'Breads',
    description: '100% whole grain loaf packed with flaxseeds, chia, toasted sunflower seeds, and rolled oats.',
    price: 85,
    weight: '400g Loaf',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Whole Wheat Flour', 'Flax Seeds', 'Sunflower Seeds', 'Rolled Oats', 'Sesame'],
    nutritionalInfo: { calories: '130 kcal / 2 slices', servings: '12 Slices', shelfLife: '4 Days' },
  },
  {
    name: 'Soft Honey Milk Bread',
    categoryName: 'Breads',
    description: 'Tender, pillowy sandwich loaf crafted with fresh dairy milk and pure natural wildflower honey.',
    price: 65,
    weight: '400g Loaf',
    image: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Full Cream Milk', 'Wheat Flour', 'Butter', 'Wildflower Honey', 'Yeast'],
    nutritionalInfo: { calories: '140 kcal / 2 slices', servings: '14 Slices', shelfLife: '4 Days' },
  },
  {
    name: 'Golden Brioche Buns (Pack of 4)',
    categoryName: 'Breads',
    description: 'Enriched, cloud-soft brioche buns brushed with golden butter glaze, ideal for gourmet burgers and sliders.',
    price: 110,
    weight: '320g (4 pcs)',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['French Butter', 'Refined Wheat Flour', 'Milk', 'Raw Sugar', 'Yeast'],
    nutritionalInfo: { calories: '180 kcal / bun', servings: '4 Buns', shelfLife: '3 Days' },
  },

  // ================= PASTRIES (5+) =================
  {
    name: 'Belgian Dark Truffle Pastry',
    categoryName: 'Pastries',
    description: 'Single-serving slice of pure decadence: 70% dark chocolate mousse layered over moist chocolate cake.',
    price: 120,
    weight: '120g',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['70% Dark Cocoa', 'Fresh Cream', 'Chocolate Ganache', 'Vanilla Sponge'],
    nutritionalInfo: { calories: '260 kcal', servings: '1 Serving', shelfLife: '2 Days' },
  },
  {
    name: 'Wild Blueberry Cheesecake Pastry',
    categoryName: 'Pastries',
    description: 'Velvety New York-style baked cheesecake crowned with wild Canadian blueberry compote on a buttery graham crust.',
    price: 160,
    weight: '140g',
    image: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Cream Cheese', 'Wild Blueberries', 'Graham Cracker Crust', 'Lemon Zest'],
    nutritionalInfo: { calories: '290 kcal', servings: '1 Serving', shelfLife: '3 Days' },
  },
  {
    name: 'Fresh Mango Cream Pastry',
    categoryName: 'Pastries',
    description: 'Airy sponge infused with Alfonso mango puree and light Chantilly cream with mango fruit pearls.',
    price: 110,
    weight: '120g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Alphonso Mango Pulp', 'Whipped Cream', 'Vanilla Chiffon Cake'],
    nutritionalInfo: { calories: '220 kcal', servings: '1 Serving', shelfLife: '2 Days' },
  },
  {
    name: 'Dutch Chocolate Éclair Pastry',
    categoryName: 'Pastries',
    description: 'Crisp choux pastry shell filled with silky vanilla bean diplomat cream and dipped in glossy Dutch chocolate.',
    price: 130,
    weight: '110g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Choux Pastry', 'Diplomat Cream', 'Dark Chocolate Glaze', 'Vanilla Bean'],
    nutritionalInfo: { calories: '240 kcal', servings: '1 Serving', shelfLife: '2 Days' },
  },
  {
    name: 'Strawberry Velveteen Pastry',
    categoryName: 'Pastries',
    description: 'Ruby strawberry glaze over light sponge layers and house-made Mahabaleshwar strawberry preserve.',
    price: 115,
    weight: '120g',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['Fresh Strawberries', 'Whipped Cream', 'Sponge Flour', 'Berry Coulis'],
    nutritionalInfo: { calories: '215 kcal', servings: '1 Serving', shelfLife: '2 Days' },
  },

  // ================= SNACKS (5+) =================
  {
    name: 'Paneer Tikka Stuffed Bun',
    categoryName: 'Snacks',
    description: 'Warm oven-baked brioche roll filled with tandoori spiced cottage cheese, peppers, and mint chutney.',
    price: 85,
    weight: '150g',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['Fresh Malai Paneer', 'Tandoori Masala', 'Bell Peppers', 'Brioche Dough'],
    nutritionalInfo: { calories: '230 kcal', servings: '1 Piece', shelfLife: '1 Day' },
  },
  {
    name: 'Baked Veggie Triangle Samosa (Pack of 4)',
    categoryName: 'Snacks',
    description: 'Crisp flaky baked pastry parcels stuffed with spiced peas, potatoes, roasted cashews, and aromatic spices.',
    price: 99,
    weight: '200g (4 pcs)',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Potatoes', 'Green Peas', 'Cashew Bits', 'Coriander', 'Cumin Pastry Dough'],
    nutritionalInfo: { calories: '120 kcal / samosa', servings: '4 Pieces', shelfLife: '2 Days' },
  },
  {
    name: 'Cheesy Jalapeño Baked Rolls',
    categoryName: 'Snacks',
    description: 'Oven-toasted golden bread roll filled with sharp cheddar, mozzarella, and pickled jalapeño relish.',
    price: 89,
    weight: '140g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Cheddar Cheese', 'Mozzarella', 'Jalapeños', 'Herb Bread Dough'],
    nutritionalInfo: { calories: '210 kcal', servings: '1 Piece', shelfLife: '1 Day' },
  },
  {
    name: 'Spiced Masala Corn Roll',
    categoryName: 'Snacks',
    description: 'Sweet golden American corn kernels sautéed in mild Indian spices encased in freshly baked bread crust.',
    price: 75,
    weight: '140g',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Sweet Corn', 'Green Chillies', 'Butter', 'Garam Masala', 'Bread Flour'],
    nutritionalInfo: { calories: '185 kcal', servings: '1 Piece', shelfLife: '1 Day' },
  },
  {
    name: 'Crispy Salt & Pepper Cashew Namkeen',
    categoryName: 'Snacks',
    description: 'Slow-roasted whole jumbo cashews tossed with freshly cracked black tellicherry peppercorns and pink salt.',
    price: 160,
    weight: '200g',
    image: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['Jumbo Cashews', 'Black Pepper', 'Pink Rock Salt', 'Pure Ghee'],
    nutritionalInfo: { calories: '160 kcal / 30g', servings: '6-7 Servings', shelfLife: '60 Days' },
  },

  // ================= PUFFS (5+) =================
  {
    name: 'Golden Veggie Curry Puff',
    categoryName: 'Puffs',
    description: 'Extremely flaky, multi-layered puff pastry filled with traditional spiced potatoes, carrots, and peas.',
    price: 45,
    weight: '120g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 1,
    ingredients: ['Laminated Puff Pastry', 'Potatoes', 'Carrots', 'Green Peas', 'Garam Masala'],
    nutritionalInfo: { calories: '210 kcal', servings: '1 Puff', shelfLife: '1 Day' },
  },
  {
    name: 'Paneer Butter Masala Puff',
    categoryName: 'Puffs',
    description: 'Flaky golden puff loaded with rich makhani gravy and soft diced cottage cheese cubes.',
    price: 55,
    weight: '130g',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 2,
    ingredients: ['Cottage Cheese (Paneer)', 'Makhani Sauce', 'Fenugreek Leaves', 'Flaky Puff Shell'],
    nutritionalInfo: { calories: '245 kcal', servings: '1 Puff', shelfLife: '1 Day' },
  },
  {
    name: 'Spiced Potato Masala Puff',
    categoryName: 'Puffs',
    description: 'Bakery classic: savory smashed potato filling tempered with mustard seeds, curry leaves, and turmeric.',
    price: 40,
    weight: '110g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 3,
    ingredients: ['Boiled Potatoes', 'Mustard Seeds', 'Curry Leaves', 'Turmeric', 'Puff Dough'],
    nutritionalInfo: { calories: '190 kcal', servings: '1 Puff', shelfLife: '1 Day' },
  },
  {
    name: 'Mushroom & Herb Flaky Puff',
    categoryName: 'Puffs',
    description: 'Button mushrooms sautéed with garlic, thyme, and black pepper folded into a crisp butter puff.',
    price: 60,
    weight: '120g',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: false,
    isAvailable: true,
    displayOrder: 4,
    ingredients: ['Button Mushrooms', 'Garlic', 'Thyme', 'Caramelized Onions', 'Puff Pastry'],
    nutritionalInfo: { calories: '195 kcal', servings: '1 Puff', shelfLife: '1 Day' },
  },
  {
    name: 'Sweet Corn & Melted Cheese Puff',
    categoryName: 'Puffs',
    description: 'Golden sweet corn with stretchy mozzarella cheese and cracked black pepper inside a crispy golden puff.',
    price: 55,
    weight: '125g',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    isVeg: true,
    isEggless: true,
    isFeatured: true,
    isAvailable: true,
    displayOrder: 5,
    ingredients: ['Sweet Corn', 'Mozzarella Cheese', 'White Sauce', 'Cracked Pepper', 'Puff Pastry'],
    nutritionalInfo: { calories: '235 kcal', servings: '1 Puff', shelfLife: '1 Day' },
  },
];
